import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { VIBE_ICONS } from "../src/vibe/vibe-icons.ts";
import {
  VIBE_PIXEL_LOGO_IDS,
  VIBE_PIXEL_LOGOS,
  type VibePixelLogo,
} from "../src/vibe/vibe-pixel-logos.ts";
import {
  VIBE_SCREEN_HEIGHT,
  VIBE_SCREEN_WIDTH,
  drawVibeScreen,
  type VibeScreenAgent,
} from "../web/src/lib/vibe";
import { VIBE_PIXEL_LOGOS as WEB_PIXEL_LOGOS } from "../web/src/lib/vibe-pixel-logos";

/**
 * The panel and the console must not drift.
 *
 * `src/vibe/vibe-icons.ts` is the one hand-drawn source; the firmware carries a
 * bit-packed copy in `visual/VibeIcons.h` because C++ cannot import TypeScript.
 * A copy is a chance to disagree, so this reads the header back and compares it
 * bit for bit — the same guard `test/pixel-glyphs.test.ts` puts on the shared
 * CJK font, and for the same reason: a mark that renders differently on the
 * device than in the preview is invisible until somebody looks at the clock.
 */
const HEADER = "device/tc002-os/app/src/visual/VibeIcons.h";

function packRow(row: string): number {
  let bits = 0;
  for (let column = 0; column < row.length; column += 1) {
    if (row[column] !== ".") bits |= 1 << (row.length - 1 - column);
  }
  return bits;
}

/** Parses the generated header back into {id: {s10, s12}} of row bitmasks. */
function readHeader(): Record<string, { s10: number[]; s12: number[] }> {
  const text = readFileSync(HEADER, "utf8");
  const body = text.slice(text.indexOf("kMarks[] = {"), text.indexOf("static const int kMarkCount"));
  const marks: Record<string, { s10: number[]; s12: number[] }> = {};
  const pattern = /\{"([a-z]+)",\s*\{([^}]*)\},\s*\{([^}]*)\}\}/g;
  for (const match of body.matchAll(pattern)) {
    const numbers = (list: string) => list.split(",").map((entry) => Number.parseInt(entry.trim(), 16));
    marks[match[1]!] = { s10: numbers(match[2]!), s12: numbers(match[3]!) };
  }
  return marks;
}

describe("vibe icon parity — one source, two panels", () => {
  const header = readHeader();

  test("the firmware header carries every mark the renderer knows", () => {
    expect(Object.keys(header).sort()).toEqual(Object.keys(VIBE_ICONS).sort());
  });

  test("every row matches bit for bit at both sizes", () => {
    for (const [id, sizes] of Object.entries(VIBE_ICONS)) {
      const packed = header[id];
      expect(packed, `${id} is missing from the firmware header`).toBeDefined();
      expect(packed!.s10, `${id} s10`).toEqual(sizes.s10.map(packRow));
      expect(packed!.s12, `${id} s12`).toEqual(sizes.s12.map(packRow));
    }
  });

  test("the grids are the sizes both sides assume", () => {
    for (const [id, sizes] of Object.entries(VIBE_ICONS)) {
      expect(sizes.s10, `${id} s10 row count`).toHaveLength(10);
      expect(sizes.s12, `${id} s12 row count`).toHaveLength(12);
      for (const row of sizes.s10) expect(row, `${id} s10 "${row}"`).toHaveLength(10);
      for (const row of sizes.s12) expect(row, `${id} s12 "${row}"`).toHaveLength(12);
    }
  });

  test("the header is regenerated, not hand-edited", () => {
    expect(readFileSync(HEADER, "utf8")).toContain("GENERATED by scripts/gen-vibe-icons.ts");
  });
});

/**
 * The same guard, for the 16x16 colour marks the per-agent page draws.
 *
 * These are the only marks on the device that carry brand colour, so a drift
 * here is not a shape that looks slightly wrong — it is Claude's orange coming
 * out grey, which nobody would notice from the console. The 2-bit indices and
 * the palette are both read back out of the header and compared with the
 * TypeScript source, because both halves have to agree for a pixel to be right.
 */
const COLOR_MARK_SIZE = 16;

function packColorRow(row: string, keys: readonly string[]): number {
  let bits = 0;
  for (let column = 0; column < row.length; column += 1) {
    const cell = row[column]!;
    if (cell === ".") continue;
    bits |= (keys.indexOf(cell) + 1) << (2 * (COLOR_MARK_SIZE - 1 - column));
  }
  return bits >>> 0;
}

/** Parses the generated header back into {id: {palette, rows}}. */
function readColorMarks(): Record<string, { palette: number[][]; rows: number[] }> {
  const text = readFileSync(HEADER, "utf8");
  const body = text.slice(
    text.indexOf("kColorMarks[] = {"),
    text.indexOf("static const int kColorMarkCount"),
  );
  const marks: Record<string, { palette: number[][]; rows: number[] }> = {};
  const pattern = /\{"([a-z]+)",\s*\{((?:\{[^}]*\},?)+)\},\s*\{([^}]*)\}\}/g;
  for (const match of body.matchAll(pattern)) {
    const palette = [...match[2]!.matchAll(/\{(\d+),(\d+),(\d+)\}/g)].map((rgb) => [
      Number(rgb[1]),
      Number(rgb[2]),
      Number(rgb[3]),
    ]);
    const rows = match[3]!.split(",").map((entry) => Number(BigInt(entry.trim().replace(/u$/, ""))));
    marks[match[1]!] = { palette, rows };
  }
  return marks;
}

describe("vibe colour-mark parity — the 16x16 art the per-agent page draws", () => {
  const header = readColorMarks();

  test("the firmware header carries every colour mark the pack declares", () => {
    expect(Object.keys(header).sort()).toEqual([...VIBE_PIXEL_LOGO_IDS].sort());
  });

  test("every row matches, two bits per pixel, leftmost column in the high bits", () => {
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const logo: VibePixelLogo = VIBE_PIXEL_LOGOS[id];
      const keys = Object.keys(logo.palette);
      const packed = header[id];
      expect(packed, `${id} is missing from the firmware header`).toBeDefined();
      expect(packed!.rows, `${id} rows`).toEqual(logo.rows.map((row) => packColorRow(row, keys)));
    }
  });

  test("each mark carries its own palette, padded to the three slots the struct has", () => {
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const logo: VibePixelLogo = VIBE_PIXEL_LOGOS[id];
      const keys = Object.keys(logo.palette);
      const expected = keys.map((key) => [...logo.palette[key]!].slice(0, 3));
      // Unused slots are black and unreachable: no row can index past the
      // colours the source declared, which the row check above already pins.
      while (expected.length < 3) expected.push([0, 0, 0]);
      expect(header[id]!.palette, `${id} palette`).toEqual(expected);
    }
  });

  test("the grids are the size both sides assume, and opaque throughout", () => {
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const logo: VibePixelLogo = VIBE_PIXEL_LOGOS[id];
      expect(logo.rows, `${id} row count`).toHaveLength(COLOR_MARK_SIZE);
      for (const row of logo.rows) expect(row, `${id} "${row}"`).toHaveLength(COLOR_MARK_SIZE);
      // Three colours is the format's ceiling: a fourth would need a third bit
      // and a different header, not a silently dropped colour.
      const keys = Object.keys(logo.palette);
      expect(keys.length, `${id} colour count`).toBeLessThanOrEqual(3);
      for (const key of keys) expect(logo.palette[key]![3], `${id} ${key} alpha`).toBe(255);
    }
  });
});

/**
 * The third consumer: the console's 屏幕预览.
 *
 * Everything above binds two sides — the hand-drawn source and the C++ header.
 * The 52x16 canvas in the VIBE tab is a THIRD renderer (web/src/lib/vibe.ts),
 * written in TypeScript against the same data, and for one release it was bound
 * by nothing: the firmware moved to these 16x16 colour marks and the preview
 * kept drawing the old monochrome `s12` grids. The console showed one thing and
 * the clock showed another, every test stayed green, and the only way to find it
 * was to look at both.
 *
 * A preview that lies is worse than no preview, because the user believes it —
 * it is presented as "what the clock shows", so they check the browser instead
 * of walking over to the panel. These read the mark straight back out of the
 * rendered frame and compare it with the FIRMWARE HEADER's own bits, not with
 * the TypeScript the header was generated from: the header is what was flashed,
 * so it is what the console has to agree with.
 */
function headerPixel(
  mark: { palette: number[][]; rows: number[] },
  x: number,
  y: number,
): [number, number, number] | null {
  const shift = 2 * (COLOR_MARK_SIZE - 1 - x);
  const index = (mark.rows[y]! >>> shift) & 0x3;
  // Index 0 is transparent — the firmware plots nothing at all, so the caller
  // expects the page's own background rather than any colour.
  if (index === 0) return null;
  const rgb = mark.palette[index - 1]!;
  return [rgb[0]!, rgb[1]!, rgb[2]!];
}

/** One per-agent page of the preview, as the console's canvas would blit it. */
function detailFrame(id: string, used = 41): Uint8ClampedArray {
  const agent: VibeScreenAgent = {
    id,
    label: id,
    plan: "",
    stale: false,
    metrics: [{ label: "Session", used, limit: 100, resetSec: -1 }],
  };
  return drawVibeScreen({ kind: "agent", agent });
}

function framePixel(frame: Uint8ClampedArray, x: number, y: number): [number, number, number] {
  const at = (y * VIBE_SCREEN_WIDTH + x) * 4;
  return [frame[at]!, frame[at + 1]!, frame[at + 2]!];
}

describe("vibe colour-mark parity — the console's preview is the third consumer", () => {
  const header = readColorMarks();

  test("the console reads the owner's source, not a copy of it", () => {
    // Same module instance, so there is no second table to drift: the browser
    // bundle re-exports src/vibe/vibe-pixel-logos.ts the way vibe-icon-grids.ts
    // re-exports vibe-icons.ts.
    expect(WEB_PIXEL_LOGOS).toBe(VIBE_PIXEL_LOGOS);
    const reexport = readFileSync(
      new URL("../web/src/lib/vibe-pixel-logos.ts", import.meta.url),
      "utf8",
    );
    expect(reexport).toContain('export * from "../../../src/vibe/vibe-pixel-logos.ts"');
  });

  test("the per-agent page draws the firmware's mark, pixel for pixel", () => {
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const mark = header[id]!;
      const frame = detailFrame(id);
      for (let y = 0; y < COLOR_MARK_SIZE; y += 1) {
        for (let x = 0; x < COLOR_MARK_SIZE; x += 1) {
          // kMarkColorY = 0 and the mark starts at x=0: 16 rows on a 16-row
          // panel is 1:1, so a grid cell IS a canvas pixel at the same address.
          expect(framePixel(frame, x, y), `${id} (${x},${y})`)
            .toEqual(headerPixel(mark, x, y) ?? [0, 0, 0]);
        }
      }
    }
  });

  test("a transparent cell is never painted — the page shows through", () => {
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const mark = header[id]!;
      const frame = detailFrame(id);
      let opaque = 0;
      let painted = 0;
      for (let y = 0; y < COLOR_MARK_SIZE; y += 1) {
        for (let x = 0; x < COLOR_MARK_SIZE; x += 1) {
          if (headerPixel(mark, x, y) !== null) opaque += 1;
          const [r, g, b] = framePixel(frame, x, y);
          if (r + g + b > 0) painted += 1;
        }
      }
      // Every mark here has an opaque palette and real holes in it, so counting
      // is enough to catch the failure that matters: treating "." as a colour
      // floods all 256 cells and buries the art in a solid block.
      expect(painted, `${id} painted cells`).toBe(opaque);
      expect(opaque, `${id} opaque cells`).toBeLessThan(COLOR_MARK_SIZE * COLOR_MARK_SIZE);
    }
    // Claude's two eyes are transparent by design and are the whole reason that
    // mark is legible at 16 px; they must stay unlit holes, not dim orange.
    const claude = detailFrame("claude");
    expect(framePixel(claude, 4, 5)).toEqual([0, 0, 0]);
    expect(framePixel(claude, 11, 5)).toEqual([0, 0, 0]);
  });

  test("the page's severity accent never reaches a brand mark", () => {
    const DANGER: [number, number, number] = [255, 69, 58];
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const calm = detailFrame(id, 41);
      const critical = detailFrame(id, 93);
      // The row is what severity owns: at 93% the value column goes red.
      expect(framePixel(critical, VIBE_SCREEN_WIDTH - 1, 5), `${id} value`).toEqual(DANGER);
      expect(framePixel(calm, VIBE_SCREEN_WIDTH - 1, 5), `${id} value`).not.toEqual(DANGER);
      for (let y = 0; y < COLOR_MARK_SIZE; y += 1) {
        for (let x = 0; x < COLOR_MARK_SIZE; x += 1) {
          // The mark is not. Same bytes at 41% and at 93%, and never the
          // accent's own colour: tinting brand art with the page's severity is
          // the same mistake as colourising a photograph.
          expect(framePixel(critical, x, y), `${id} (${x},${y})`)
            .toEqual(framePixel(calm, x, y));
          expect(framePixel(critical, x, y), `${id} (${x},${y})`).not.toEqual(DANGER);
        }
      }
    }
  });

  test("the mark stays inside its own 16 columns", () => {
    // kDetailRowX = 17 with x=16 as the gutter. A mark that bled one column
    // right would overprint the metric's initial on the real panel.
    for (const id of VIBE_PIXEL_LOGO_IDS) {
      const frame = detailFrame(id);
      for (let y = 0; y < VIBE_SCREEN_HEIGHT; y += 1) {
        expect(framePixel(frame, COLOR_MARK_SIZE, y), `${id} gutter row ${y}`).toEqual([0, 0, 0]);
      }
    }
  });
});
