import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { VIBE_ICONS } from "../src/vibe/vibe-icons.ts";

/**
 * The panel and the console must not drift.
 *
 * `src/vibe/vibe-icons.ts` is the one hand-drawn source; the firmware carries a
 * bit-packed copy in `visual/VibeIcons.h` because C++ cannot import TypeScript.
 * A copy is a chance to disagree, so this reads the header back and compares it
 * bit for bit — the same guard `test/pixel-glyphs.test.ts` puts on the shared
 * CJK font, and for the same reason: a mark that renders differently on the
 * device than in the preview is invisible until somebody looks at the clock.
 */
const HEADER = "device/tc002-os/app/src/visual/VibeIcons.h";

function packRow(row: string): number {
  let bits = 0;
  for (let column = 0; column < row.length; column += 1) {
    if (row[column] !== ".") bits |= 1 << (row.length - 1 - column);
  }
  return bits;
}

/** Parses the generated header back into {id: {s10, s12}} of row bitmasks. */
function readHeader(): Record<string, { s10: number[]; s12: number[] }> {
  const text = readFileSync(HEADER, "utf8");
  const body = text.slice(text.indexOf("kMarks[] = {"), text.indexOf("static const int kMarkCount"));
  const marks: Record<string, { s10: number[]; s12: number[] }> = {};
  const pattern = /\{"([a-z]+)",\s*\{([^}]*)\},\s*\{([^}]*)\}\}/g;
  for (const match of body.matchAll(pattern)) {
    const numbers = (list: string) => list.split(",").map((entry) => Number.parseInt(entry.trim(), 16));
    marks[match[1]!] = { s10: numbers(match[2]!), s12: numbers(match[3]!) };
  }
  return marks;
}

describe("vibe icon parity — one source, two panels", () => {
  const header = readHeader();

  test("the firmware header carries every mark the renderer knows", () => {
    expect(Object.keys(header).sort()).toEqual(Object.keys(VIBE_ICONS).sort());
  });

  test("every row matches bit for bit at both sizes", () => {
    for (const [id, sizes] of Object.entries(VIBE_ICONS)) {
      const packed = header[id];
      expect(packed, `${id} is missing from the firmware header`).toBeDefined();
      expect(packed!.s10, `${id} s10`).toEqual(sizes.s10.map(packRow));
      expect(packed!.s12, `${id} s12`).toEqual(sizes.s12.map(packRow));
    }
  });

  test("the grids are the sizes both sides assume", () => {
    for (const [id, sizes] of Object.entries(VIBE_ICONS)) {
      expect(sizes.s10, `${id} s10 row count`).toHaveLength(10);
      expect(sizes.s12, `${id} s12 row count`).toHaveLength(12);
      for (const row of sizes.s10) expect(row, `${id} s10 "${row}"`).toHaveLength(10);
      for (const row of sizes.s12) expect(row, `${id} s12 "${row}"`).toHaveLength(12);
    }
  });

  test("the header is regenerated, not hand-edited", () => {
    expect(readFileSync(HEADER, "utf8")).toContain("GENERATED by scripts/gen-vibe-icons.ts");
  });
});
