// Hand-authored pixel art for the LED panel — NOT generated from the SVGs.
//
// Area-averaging a vector mark into a 10–12 px grid destroys it: every logo here
// is built from strokes 1–2 px wide at this scale, so the mean coverage of a
// stroke falls under any sane threshold and the shape dissolves (the OpenAI knot
// became a filled disc, the Cursor cube a blob). These grids are drawn by hand
// against the real marks instead, trading fidelity for the one thing that matters
// at 52x16: staying recognisable. `src/assets/vibe-icons/*.svg` keeps the vector
// originals, which the console renders directly.
//
// Rows: "." = off, "*" = dim (55 % of the ink colour), "x" = full.
// s10 feeds the two-agent strip, s12 the single-agent detail page. `gauge` is
// not a vendor: it is the neutral mark the empty state falls back to.

export type VibeIconGrid = readonly string[];

export interface VibeIconSizes {
  readonly s10: VibeIconGrid;
  readonly s12: VibeIconGrid;
}

export const VIBE_ICONS: Record<string, VibeIconSizes> = {
  claude: {
    s10: [
      "....xx....",
      ".x..xx..x.",
      "..x.xx.x..",
      "...xxxx...",
      "xxxxxxxxxx",
      "xxxxxxxxxx",
      "...xxxx...",
      "..x.xx.x..",
      ".x..xx..x.",
      "....xx....",
    ],
    s12: [
      ".....xx.....",
      ".x...xx...x.",
      "..x..xx..x..",
      "...x.xx.x...",
      "....xxxx....",
      "xxxxxxxxxxxx",
      "xxxxxxxxxxxx",
      "....xxxx....",
      "...x.xx.x...",
      "..x..xx..x..",
      ".x...xx...x.",
      ".....xx.....",
    ],
  },
  codex: {
    s10: [
      "...xxxx...",
      "..x....x..",
      ".x......x.",
      "x...xx...x",
      "x..x.x...x",
      "x...x..x.x",
      "x...x.xx.x",
      ".x......x.",
      "..x....x..",
      "...xxxx...",
    ],
    s12: [
      "....xxxx....",
      "..xx....xx..",
      ".x........x.",
      "x....xx....x",
      "x...x.x....x",
      "x..x..x....x",
      "x....x..x..x",
      "x....x...x.x",
      "x.....xxx..x",
      ".x........x.",
      "..xx....xx..",
      "....xxxx....",
    ],
  },
  cursor: {
    s10: [
      "....xx....",
      "..xx..xx..",
      ".x......x.",
      "x........x",
      "x..xxxx..x",
      "x...xxx..x",
      "x....xx..x",
      ".x....x.x.",
      "..xx..xx..",
      "....xx....",
    ],
    s12: [
      ".....xx.....",
      "...xx..xx...",
      ".xx......xx.",
      "x..........x",
      "x..........x",
      "x...xxxxx..x",
      "x....xxxx..x",
      "x.....xxx..x",
      "x......xx..x",
      ".xx.....x.x.",
      "...xx..xx...",
      ".....xx.....",
    ],
  },
  antigravity: {
    s10: [
      "....xx....",
      "...xxxx...",
      "..xx..xx..",
      "..xx..xx..",
      ".xx....xx.",
      ".xx....xx.",
      ".xx....xx.",
      "xx......xx",
      "xx......xx",
      "xxx....xxx",
    ],
    s12: [
      ".....xx.....",
      "....xxxx....",
      "...xx..xx...",
      "...xx..xx...",
      "..xx....xx..",
      "..xx....xx..",
      ".xx......xx.",
      ".xx......xx.",
      ".xx......xx.",
      "xx........xx",
      "xx........xx",
      "xxx......xxx",
    ],
  },
  copilot: {
    s10: [
      "..x....x..",
      "...x..x...",
      ".xxxxxxxx.",
      "xxxxxxxxxx",
      "x.xx..xx.x",
      "x.xx..xx.x",
      "xxxxxxxxxx",
      ".xxxxxxxx.",
      "..xxxxxx..",
      "...xxxx...",
    ],
    s12: [
      "..x......x..",
      "...x....x...",
      ".xxxxxxxxxx.",
      "xxxxxxxxxxxx",
      "xx.xx..xx.xx",
      "xx.xx..xx.xx",
      "xxxxxxxxxxxx",
      "xxxxxxxxxxxx",
      ".xxxxxxxxxx.",
      "..xxxxxxxx..",
      "...xxxxxx...",
      "............",
    ],
  },
  devin: {
    s10: [
      "..xx..xx..",
      ".xxxxxxxx.",
      "..xx..xx..",
      "..........",
      "xx......xx",
      "xx......xx",
      "..........",
      "..xx..xx..",
      ".xxxxxxxx.",
      "..xx..xx..",
    ],
    s12: [
      "...xx...xx..",
      "..xxxx.xxxx.",
      "...xx...xx..",
      "............",
      ".xx......xx.",
      "xxxx....xxxx",
      ".xx......xx.",
      "............",
      "...xx...xx..",
      "..xxxx.xxxx.",
      "...xx...xx..",
      "............",
    ],
  },
  grok: {
    s10: [
      "...xxx...x",
      ".x.....xx.",
      "x......x.x",
      "x.....x..x",
      "x....x...x",
      "x...x....x",
      "x..x.....x",
      ".xx....xx.",
      "x..xxx....",
      "..........",
    ],
    s12: [
      "....xxxx...x",
      "..xx....xxx.",
      ".x.......xx.",
      "x.......x..x",
      "x......x...x",
      "x.....x....x",
      "x....x.....x",
      "x...x......x",
      ".x.x......x.",
      "..xx....xx..",
      ".x..xxxx....",
      "x...........",
    ],
  },
  opencode: {
    s10: [
      "xxxxxxxxxx",
      "xxxxxxxxxx",
      "xx......xx",
      "xx......xx",
      "xx......xx",
      "xx......xx",
      "xx......xx",
      "xx......xx",
      "xxxxxxxxxx",
      "xxxxxxxxxx",
    ],
    s12: [
      "xxxxxxxxxxxx",
      "xxxxxxxxxxxx",
      "xx........xx",
      "xx........xx",
      "xx........xx",
      "xx........xx",
      "xx........xx",
      "xx........xx",
      "xx........xx",
      "xx........xx",
      "xxxxxxxxxxxx",
      "xxxxxxxxxxxx",
    ],
  },
  openrouter: {
    s10: [
      "........xx",
      "......xxxx",
      "...xxxxx..",
      ".xxx......",
      "xx........",
      "xx........",
      ".xxx......",
      "...xxxxx..",
      "......xxxx",
      "........xx",
    ],
    s12: [
      "..........xx",
      "........xxxx",
      ".....xxxxxx.",
      "..xxxxx.....",
      ".xxx........",
      "xxx.........",
      "xxx.........",
      ".xxx........",
      "..xxxxx.....",
      ".....xxxxxx.",
      "........xxxx",
      "..........xx",
    ],
  },
  zai: {
    s10: [
      ".xxxxxxxx.",
      ".xxxxxxxx.",
      "......xx..",
      ".....xx...",
      "....xx....",
      "...xx.....",
      "..xx......",
      ".xx.......",
      ".xxxxxxxx.",
      ".xxxxxxxx.",
    ],
    s12: [
      ".xxxxxxxxxx.",
      ".xxxxxxxxxx.",
      "........xx..",
      ".......xx...",
      "......xx....",
      ".....xx.....",
      "....xx......",
      "...xx.......",
      "..xx........",
      ".xx.........",
      ".xxxxxxxxxx.",
      ".xxxxxxxxxx.",
    ],
  },
  gauge: {
    s10: [
      "..xxxxxx..",
      ".x......x.",
      "x...x....x",
      "x..x.....x",
      "x.x......x",
      "x........x",
      ".x......x.",
      "..xxxxxx..",
      "..........",
      "..........",
    ],
    s12: [
      "...xxxxxx...",
      "..x......x..",
      ".x........x.",
      "x....x.....x",
      "x...x......x",
      "x..x.......x",
      "x.xx.......x",
      "x..........x",
      ".x........x.",
      "..x......x..",
      "...xxxxxx...",
      "............",
    ],
  },
};
