#ifndef VISUAL_VIBEICONS_H_
#define VISUAL_VIBEICONS_H_
#include <stdint.h>
// GENERATED by scripts/gen-vibe-icons.ts from src/vibe/vibe-icons.ts and
// src/vibe/vibe-pixel-logos.ts — do not edit by hand. The same hand-drawn grids
// the LED channel renderer uses, so a mark reads identically on the panel and
// in the console's preview; test/vibe-icons-parity.test.ts holds the two sides
// together.
//
// Each `Mark` row uses the low `size` bits, bit(size-1) = leftmost column.
// `s10` feeds the two-agent overview, `s12` is the monochrome fallback on a
// per-agent page for a vendor with no colour mark below.
namespace tcos {
namespace vibeicons {

struct Mark {
  const char* id;
  uint16_t s10[10];
  uint16_t s12[12];
};

static const Mark kMarks[] = {
  {"claude",
   {0x0000,0x00fc,0x017a,0x01fe,0x00fc,0x00fc,0x00fc,0x00b4,0x00b4,0x0000},
   {0x0060,0x0462,0x0264,0x0168,0x00f0,0x0fff,0x0fff,0x00f0,0x0168,0x0264,0x0462,0x0060}},
  {"codex",
   {0x00fc,0x01fe,0x03ff,0x037f,0x03bf,0x03df,0x03bf,0x037f,0x01c3,0x00fc},
   {0x00f0,0x030c,0x0402,0x0861,0x08a1,0x0921,0x0849,0x0845,0x0839,0x0402,0x030c,0x00f0}},
  {"gauge",
   {0x00fc,0x0102,0x0221,0x0241,0x0281,0x0201,0x0102,0x00fc,0x0000,0x0000},
   {0x01f8,0x0204,0x0402,0x0841,0x0881,0x0901,0x0b01,0x0801,0x0402,0x0204,0x01f8,0x0000}},
  {"grok",
   {0x0001,0x00f2,0x010c,0x0219,0x0231,0x0261,0x02c1,0x0181,0x030e,0x0278},
   {0x00f1,0x030e,0x0406,0x0809,0x0811,0x0821,0x0841,0x0881,0x0502,0x030c,0x04f0,0x0800}},
  {"opencode",
   {0x0000,0x00fc,0x00fc,0x00cc,0x00cc,0x00cc,0x00cc,0x00fc,0x00fc,0x0000},
   {0x0fff,0x0fff,0x0c03,0x0c03,0x0c03,0x0c03,0x0c03,0x0c03,0x0c03,0x0c03,0x0fff,0x0fff}},
};

static const int kMarkCount = 5;

/** The mark for a provider id, or null when the firmware has never heard of it. */
inline const Mark* find(const char* id) {
  if (id == 0) return 0;
  for (int i = 0; i < kMarkCount; ++i) {
    const char* a = kMarks[i].id;
    const char* b = id;
    while (*a != 0 && *a == *b) { ++a; ++b; }
    if (*a == 0 && *b == 0) return &kMarks[i];
  }
  return 0;
}

// The 16x16 provider art from src/vibe/vibe-pixel-logos.ts, drawn 1:1 on the
// per-agent page — the panel is exactly 16 rows tall, so there is no scaling
// and therefore no resampling, which is what that art's README forbids.
//
// Two bits per pixel: 0 = transparent (not plotted, the page shows through),
// 1..3 index `palette`. `rows[y]` holds column 0 in bits 31..30, so the same
// "leftmost is highest" rule as `Mark` above. 9 bytes of palette plus
// 64 bytes of pixels per mark; unused palette slots are black and unreachable.
struct ColorMark {
  const char* id;
  uint8_t palette[3][3];
  uint32_t rows[16];
};

static const int kColorMarkSize = 16;
static const int kColorMarkBpp = 2;

static const ColorMark kColorMarks[] = {
  {"claude",
   {{231,117,61},{0,0,0},{0,0,0}},
   {0x00000000u,0x00000000u,0x00000000u,0x01555540u,0x01555540u,0x05155450u,0x05555550u,0x01555540u,0x01555540u,0x01555540u,0x01441140u,0x01441140u,0x01441140u,0x00000000u,0x00000000u,0x00000000u}},
  {"codex",
   {{124,131,246},{45,86,232},{255,255,255}},
   {0x00155400u,0x01555540u,0x05555550u,0x15555554u,0x17d55554u,0x557d5556u,0x5557d5aau,0x557d6aaau,0x57daaaaau,0x56aaaaaau,0x2aaaffe8u,0x2aaaaaa8u,0x0aaaaaa0u,0x02aaaa80u,0x002aa800u,0x00000000u}},
  {"grok",
   {{247,247,245},{174,177,174},{88,92,90}},
   {0x00000000u,0x0000000fu,0x003aac38u,0x00d557d0u,0x035c0350u,0x01400d50u,0x0dc03750u,0x0900e090u,0x09038090u,0x09c30050u,0x0d800360u,0x01800d40u,0x0a2695c0u,0x3c395800u,0x30000000u,0x00000000u}},
  {"opencode",
   {{247,247,245},{0,0,0},{0,0,0}},
   {0x00000000u,0x00000000u,0x01555540u,0x01555540u,0x01400140u,0x01400140u,0x01400140u,0x01400140u,0x01400140u,0x01400140u,0x01400140u,0x01400140u,0x01555540u,0x01555540u,0x00000000u,0x00000000u}},
};

static const int kColorMarkCount = 4;

/** The 16x16 colour mark for a provider id, or null when this build has none. */
inline const ColorMark* findColor(const char* id) {
  if (id == 0) return 0;
  for (int i = 0; i < kColorMarkCount; ++i) {
    const char* a = kColorMarks[i].id;
    const char* b = id;
    while (*a != 0 && *a == *b) { ++a; ++b; }
    if (*a == 0 && *b == 0) return &kColorMarks[i];
  }
  return 0;
}

}  // namespace vibeicons
}  // namespace tcos

#endif  // VISUAL_VIBEICONS_H_
