/**
 * Mirrors the firmware's dot-matrix font into the web preview.
 *
 * The device renders lyrics from two generated headers — `CjkFont.h` (12x12
 * full-width) and `LatinFont.h` (6x12 half-width) — rasterised offline from
 * Fusion Pixel 12px by `device/tc002-lyrics-player/tools/gen-fonts.py`. The
 * preview used to re-rasterise text through a webfont at runtime, which meant
 * it depended on a font the browser may not have (the npm package ships the
 * latin subset only, so every hanzi fell back to the system UI font and turned
 * to mush once thresholded).
 *
 * So the preview reads the same bits the panel does. This script parses the two
 * headers and emits `web/src/lib/pixel-glyph-data.ts`, a base64 blob laid out
 * as:
 *
 *   [0]                     cjkCount codepoints, uint16 LE, strictly ascending
 *   [cjkCount * 2]          cjkCount * 18 bytes of CJK rows, bit11 = leftmost
 *   [... + cjkCount * 18]   latinCount * 12 latin rows, uint8, bit5 = leftmost
 *
 * CJK rows are 12 bits, so a pair of rows packs into three bytes rather than
 * wasting a nibble each: [aaaaaaaa][aaaabbbb][bbbbbbbb]. That is 18 bytes per
 * glyph instead of 24, and ~40 KB off the generated module.
 *
 * Usage: bun run scripts/gen-web-glyphs.ts
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
// One copy for every firmware and for the browser preview: device/shared-visual.
const visualDir = join(root, "device/shared-visual");
const outputPath = join(root, "web/src/lib/pixel-glyph-data.ts");

const CELL_HEIGHT = 12;
const LATIN_FIRST = 0x20;
const LATIN_LAST = 0x7e;

interface ParsedGlyph {
  codepoint: number;
  rows: number[];
}

// Both headers declare glyphs as `{0xNNNN,{0xrrr,0xrrr,...}},` — one entry per
// line, twelve row masks each.
function parseGlyphHeader(source: string, label: string): ParsedGlyph[] {
  const glyphs: ParsedGlyph[] = [];
  for (const match of source.matchAll(/\{0x([0-9A-Fa-f]{4}),\{([^}]*)\}\}/g)) {
    const rows = match[2]!.split(",").map((value) => Number.parseInt(value, 16));
    if (rows.length !== CELL_HEIGHT || rows.some((row) => !Number.isInteger(row))) {
      throw new Error(`${label}: glyph 0x${match[1]} has ${rows.length} usable rows`);
    }
    glyphs.push({ codepoint: Number.parseInt(match[1]!, 16), rows });
  }
  if (glyphs.length === 0) throw new Error(`${label}: no glyphs found`);
  return glyphs;
}

const [cjkSource, latinSource] = await Promise.all([
  readFile(join(visualDir, "CjkFont.h"), "utf8"),
  readFile(join(visualDir, "LatinFont.h"), "utf8"),
]);

const cjkGlyphs = parseGlyphHeader(cjkSource, "CjkFont.h");
const latinGlyphs = parseGlyphHeader(latinSource, "LatinFont.h");

// The runtime binary-searches the codepoints and indexes latin directly, so
// both invariants have to hold before anything is written.
for (let index = 1; index < cjkGlyphs.length; index += 1) {
  if (cjkGlyphs[index]!.codepoint <= cjkGlyphs[index - 1]!.codepoint) {
    throw new Error("CjkFont.h: codepoints must be strictly ascending");
  }
}
if (cjkGlyphs.at(-1)!.codepoint > 0xffff) {
  throw new Error("CjkFont.h: codepoints must fit in uint16");
}
if (cjkGlyphs.some((glyph) => glyph.rows.some((row) => row > 0xfff))) {
  throw new Error("CjkFont.h: row masks must fit in 12 bits");
}
if (
  latinGlyphs.length !== LATIN_LAST - LATIN_FIRST + 1
  || latinGlyphs.some((glyph, index) => glyph.codepoint !== LATIN_FIRST + index)
) {
  throw new Error(`LatinFont.h: expected ASCII 0x20..0x7E contiguous`);
}
if (latinGlyphs.some((glyph) => glyph.rows.some((row) => row > 0x3f))) {
  throw new Error("LatinFont.h: row masks must fit in 6 bits");
}

const cjkCount = cjkGlyphs.length;
const latinCount = latinGlyphs.length;
const CJK_PACKED_BYTES = CELL_HEIGHT / 2 * 3;
const codepointBytes = cjkCount * 2;
const cjkRowBytes = cjkCount * CJK_PACKED_BYTES;
const latinRowBytes = latinCount * CELL_HEIGHT;
const blob = new Uint8Array(codepointBytes + cjkRowBytes + latinRowBytes);
const view = new DataView(blob.buffer);

cjkGlyphs.forEach((glyph, index) => {
  view.setUint16(index * 2, glyph.codepoint, true);
  const base = codepointBytes + index * CJK_PACKED_BYTES;
  for (let pair = 0; pair < CELL_HEIGHT / 2; pair += 1) {
    const first = glyph.rows[pair * 2]!;
    const second = glyph.rows[pair * 2 + 1]!;
    blob[base + pair * 3] = first >> 4;
    blob[base + pair * 3 + 1] = ((first & 0xf) << 4) | (second >> 8);
    blob[base + pair * 3 + 2] = second & 0xff;
  }
});
latinGlyphs.forEach((glyph, index) => {
  glyph.rows.forEach((row, rowIndex) => {
    blob[codepointBytes + cjkRowBytes + index * CELL_HEIGHT + rowIndex] = row;
  });
});

const module = `// Generated by scripts/gen-web-glyphs.ts from the firmware's CjkFont.h and
// LatinFont.h -- do not edit by hand. Keeping the preview on the panel's own
// glyphs is what makes the two render identically.
export const PIXEL_GLYPH_CELL_HEIGHT = ${CELL_HEIGHT};
export const PIXEL_GLYPH_CJK_COUNT = ${cjkCount};
export const PIXEL_GLYPH_LATIN_FIRST = 0x${LATIN_FIRST.toString(16)};
export const PIXEL_GLYPH_LATIN_LAST = 0x${LATIN_LAST.toString(16)};
export const PIXEL_GLYPH_BLOB_BASE64 =
  "${Buffer.from(blob).toString("base64")}";
`;

await writeFile(outputPath, module, "utf8");
console.log(
  `Wrote ${outputPath}: ${cjkCount} CJK + ${latinCount} latin glyphs, `
    + `${blob.length} bytes (${Math.round(module.length / 1024)} KB module)`,
);
