/**
 * Regenerates the two consumers of the VIBE marks:
 *
 *   - `web/src/lib/vibe-icon-svg.ts` — the console's vector marks, inlined from
 *     `src/assets/vibe-icons/*.svg`.
 *   - `device/tc002-os/app/src/visual/VibeIcons.h` — the SAME pixel grids the
 *     LED renderer uses, bit-packed for the firmware.
 *
 * The console renders each vendor's real vector mark, so this is a plain inline
 * of the SVG sources — no rasterisation. The LED grids in `src/vibe/vibe-icons.ts`
 * used to be generated from these same files and are **not** any more: at 10–12 px
 * every one of these marks is thinner than a pixel and area-averaging dissolved
 * it (the OpenAI knot became a disc, the Cursor cube a blob). Those grids are
 * hand-drawn pixel art now and are edited directly; see that file's header.
 *
 * The firmware header is generated from `src/vibe/vibe-icons.ts` rather than
 * from the SVGs, because those grids are hand-drawn (see that file's header).
 * One source, two panels: `test/vibe-icons-parity.test.ts` asserts the header
 * matches the TypeScript bit for bit, the same guard `test/pixel-glyphs.test.ts`
 * puts on the shared CJK font.
 *
 * Run after adding or replacing a mark, or after editing a grid:
 *
 *   bun run scripts/gen-vibe-icons.ts
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { VIBE_ICONS } from "../src/vibe/vibe-icons.ts";

const REPO = fileURLToPath(new URL("..", import.meta.url));
const ICON_DIR = join(REPO, "src/assets/vibe-icons");

const files = readdirSync(ICON_DIR).filter((file) => file.endsWith(".svg")).sort();

let module = `// GENERATED by scripts/gen-vibe-icons.ts — do not edit by hand.
// Vendor marks for the VIBE tab's provider list, inlined from
// src/assets/vibe-icons/. Third-party brand marks, used nominatively to name
// each service; the LED panel uses the hand-drawn grids in src/vibe/vibe-icons.ts.

export const VIBE_ICON_SVG: Record<string, string> = {
`;
for (const file of files) {
  const svg = readFileSync(join(ICON_DIR, file), "utf8").replace(/\r?\n\s*/g, " ").trim();
  module += `  ${file.replace(/\.svg$/, "")}: ${JSON.stringify(svg)},\n`;
}
module += `};\n`;

writeFileSync(join(REPO, "web/src/lib/vibe-icon-svg.ts"), module);

// --- the firmware's copy of the same grids -----------------------------------
// Rows are packed low-bit-last so `bit(size-1)` is the leftmost column, matching
// the shared font headers' convention (`bit5 = leftmost` at 6 px wide).
function packRows(rows: readonly string[]): string[] {
  const width = rows[0]!.length;
  return rows.map((row) => {
    let bits = 0;
    for (let column = 0; column < width; column += 1) {
      if (row[column] !== ".") bits |= 1 << (width - 1 - column);
    }
    return `0x${bits.toString(16).padStart(4, "0")}`;
  });
}

const names = Object.keys(VIBE_ICONS).sort();
let header = `#ifndef VISUAL_VIBEICONS_H_
#define VISUAL_VIBEICONS_H_
#include <stdint.h>
// GENERATED by scripts/gen-vibe-icons.ts from src/vibe/vibe-icons.ts — do not
// edit by hand. The same hand-drawn grids the LED channel renderer uses, so a
// mark reads identically on the panel and in the console's preview;
// test/vibe-icons-parity.test.ts holds the two sides together.
//
// Each row uses the low \`size\` bits, bit(size-1) = leftmost column. \`s10\` feeds
// the two-agent overview, \`s12\` the per-agent page.
namespace tcos {
namespace vibeicons {

struct Mark {
  const char* id;
  uint16_t s10[10];
  uint16_t s12[12];
};

static const Mark kMarks[] = {
`;
for (const name of names) {
  const sizes = VIBE_ICONS[name]!;
  header += `  {"${name}",
`;
  header += `   {${packRows(sizes.s10).join(",")}},
`;
  header += `   {${packRows(sizes.s12).join(",")}}},
`;
}
header += `};

static const int kMarkCount = ${names.length};

/** The mark for a provider id, or null when the firmware has never heard of it. */
inline const Mark* find(const char* id) {
  if (id == 0) return 0;
  for (int i = 0; i < kMarkCount; ++i) {
    const char* a = kMarks[i].id;
    const char* b = id;
    while (*a != 0 && *a == *b) { ++a; ++b; }
    if (*a == 0 && *b == 0) return &kMarks[i];
  }
  return 0;
}

}  // namespace vibeicons
}  // namespace tcos

#endif  // VISUAL_VIBEICONS_H_
`;
writeFileSync(join(REPO, "device/tc002-os/app/src/visual/VibeIcons.h"), header);

console.log(
  `gen-vibe-icons: ${files.length} marks → web/src/lib/vibe-icon-svg.ts, `
  + `${names.length} grids → device/tc002-os/app/src/visual/VibeIcons.h`,
);
